package com.rufeng.system.business.service.impl;


import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.rufeng.common.core.db.Pager;
import com.rufeng.system.api.domain.SysOperLog;
import com.rufeng.system.business.mapper.ISysOperLogDao;
import com.rufeng.system.business.service.ISysOperLogService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;


/**
 * 操作日志记录 服务接口实现
 *
 * @version v1.0.0
 * @auther chengen
 * @date 2020/12/18 18:24
 */
@Service
public class SysOperLogServiceImpl extends ServiceImpl<ISysOperLogDao, SysOperLog> implements ISysOperLogService {
    private Logger log = LoggerFactory.getLogger(SysOperLogServiceImpl.class);

    @Autowired
    private ISysOperLogDao sysoperlogDao;

    @Override
    public SysOperLog get(Integer operid) throws Exception {
        log.debug("###[服务] 开始查询操作日志记录 operid=[{}]. ", operid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        SysOperLog operLog = sysoperlogDao.selectById(operid);
        log.info("###[服务] 完成查询操作日志记录 operLog=[{}]", operLog);
        return operLog;
    }

    @Override
    public List<SysOperLog> list(SysOperLog operLog) throws Exception {
        log.debug("###[服务] 开始根据条件{}查询操作日志记录,operLog=[{}]", operLog);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        QueryWrapper<SysOperLog> sysoperlogWrapper = new QueryWrapper<>();
        sysoperlogWrapper.setEntity(operLog);
        List<SysOperLog> operLogs = sysoperlogDao.selectList(sysoperlogWrapper);
        log.info("###[服务] 完成查询操作日志记录 operLogs=[{}]", operLogs);
        return operLogs;
    }

    @Override
    public IPage<SysOperLog> listPager(SysOperLog operLog, Pager page) throws Exception {
        log.debug("###[服务] 开始根据条件{}分页查询操作日志记录,operLog=[{}],page=[{}]", operLog, page);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        Page<SysOperLog> pageParam = new Page<>(page.getCurrentPage(), page.getTotalSize()); // 当前页码，每页条数
        QueryWrapper<SysOperLog> sysoperlogWrapper = new QueryWrapper<>();
        sysoperlogWrapper.setEntity(operLog);
        IPage<SysOperLog> pu = sysoperlogDao.selectPage(pageParam, sysoperlogWrapper);
        log.info("###[服务] 完成分页查询操作日志记录 pu=[{}]", pu);
        return pu;
    }

    @Override
    public boolean add(SysOperLog operLog) throws Exception {
        log.debug("###[服务] 开始添加新操作日志记录, operLog=[{}]", operLog);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = save(operLog);
        log.info("###[服务] 完成添加新操作日志记录，flag=[{}]", flag);
        return flag;
    }

    @Override
    public boolean update(SysOperLog operLog) throws Exception {
        log.debug("###[服务] 开始根据条件{}修改操作日志记录,operLog=[{}]", operLog);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = updateById(operLog);
        log.info("###[服务] 完成修改操作日志记录，flag=[{}]", flag);
        return flag;
    }

    @Override
    public boolean delete(Integer operid) throws Exception {
        log.debug("###[服务] 开始根据条件{}删除操作日志记录,operid=[{}]", operid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = removeById(operid);
        log.info("###[服务] 完成删除操作日志记录，flag=[{}]", flag);
        return flag;
    }
}
