package com.rufeng.system.business.service.impl;

import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.service.IService;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.rufeng.common.core.db.Pager;
import com.rufeng.system.api.domain.SysRole;
import com.rufeng.system.business.domain.po.SysRoleMenu;
import com.rufeng.system.business.mapper.ISysRoleMenuDao;
import com.rufeng.system.business.service.ISysRoleMenuService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Service
public class SysRoleMenuServiceImpl extends ServiceImpl<ISysRoleMenuDao, SysRoleMenu> implements ISysRoleMenuService {
    private Logger log = LoggerFactory.getLogger(SysRoleMenuServiceImpl.class);
    @Autowired
    private ISysRoleMenuDao sysRoleMenuDao;


    @Override
    public List<SysRoleMenu> getByRoleId(Integer roleid) {
        log.debug("###[服务] 开始根据条件{}查询角色与菜单信息,roleid=[{}]", roleid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        QueryWrapper<SysRoleMenu> queryWrapper = new QueryWrapper<>();
        queryWrapper.eq("roleid", roleid);
        List<SysRoleMenu> list = list(queryWrapper);
        log.info("###[服务] 完成查询角色与菜单信息 list=[{}]", list);
        return list;
    }


    @Override
    public List<SysRoleMenu> list(SysRoleMenu roleMenu) {
        log.debug("###[服务] 开始根据条件{}查询角色与菜单信息,roleMenu=[{}]", roleMenu);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        QueryWrapper<SysRoleMenu> queryWrapper = new QueryWrapper<>();
        List<SysRoleMenu> list = list(queryWrapper);
        log.info("###[服务] 完成分页查询角色与菜单信息 list=[{}]", list);
        return list;
    }


    @Override
    public boolean deleteSysRole(Integer roleid) throws Exception {
        log.debug("###[服务] 开始根据角色id删除信息 roleid=[{}]", roleid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        Map<String, Object> map = new HashMap<>();
        map.put("roleid", roleid);
        boolean flag = removeByMap(map);
        log.info("###[服务] 完成根据角色id删除信息 flag=[{}]", flag);
        return flag;
    }
}
