package com.rufeng.system.business.controller;


import com.baomidou.mybatisplus.core.metadata.IPage;
import com.rufeng.common.core.db.Pager;
import com.rufeng.common.core.web.controller.BaseController;
import com.rufeng.common.core.web.domain.R;
import com.rufeng.common.log.annotation.Log;
import com.rufeng.common.log.enums.BusinessType;
import com.rufeng.system.business.domain.po.SysConfig;
import com.rufeng.system.business.service.ISysConfigService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;


/**
 * 参数配置控制器
 *
 * @version v1.0.0
 * @since jdk1.8+
 */
@RestController
@RequestMapping("config")
public class SysConfigController extends BaseController {

    @Autowired
    private ISysConfigService sysconfigService;

    /**
     * 获取参数配置
     *
     * @param configid 参数主键
     * @return ResultData
     */
    @Log(title = "获取参数配置", businessType = BusinessType.SELECT)
    @RequestMapping(value = "/get/{configid}", method = {RequestMethod.GET})
    public R<SysConfig> get(@PathVariable String configid) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        SysConfig sysconfig = sysconfigService.get(configid);
        return R.ok(sysconfig);
    }

    /**
     * 查询参数配置
     *
     * @param sysconfig 参数配置对象
     * @return ResultData
     */
    @RequestMapping(value = "/list", method = {RequestMethod.GET})
    public R<List<SysConfig>> list(SysConfig sysconfig) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        List<SysConfig> lists = sysconfigService.list(sysconfig);
        return R.ok(lists);
    }


    /**
     * 分页查询参数配置
     *
     * @param page      分页对象
     * @param sysconfig 参数配置对象
     * @return ResultData
     */
    @RequestMapping(value = "/list-by-page", method = {RequestMethod.GET})
    public R<IPage<SysConfig>> listPager(SysConfig sysconfig, Pager page) throws Exception {
        IPage<SysConfig> configIPage = sysconfigService.listPager(sysconfig, page);
        return R.ok(configIPage);
    }

    /**
     * 添加参数配置
     *
     * @param sysconfig 参数配置对象
     * @return ResultData
     */
    @Log(title = "添加参数配置", businessType = BusinessType.INSERT)
    @RequestMapping(value = "/add", method = {RequestMethod.POST})
    public R<Boolean> add(@RequestBody SysConfig sysconfig) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = sysconfigService.add(sysconfig);
        return R.ok(flag);
    }

    /**
     * 更新参数配置
     *
     * @param sysconfig 参数配置对象
     * @return ResultData
     */
    @Log(title = "更新参数配置", businessType = BusinessType.UPDATE)
    @RequestMapping(value = "/update", method = {RequestMethod.PUT})
    public R<Boolean> update(@RequestBody SysConfig sysconfig) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = sysconfigService.update(sysconfig);
        return R.ok(flag);
    }

    /**
     * 删除参数配置
     *
     * @param configid 参数主键
     * @return ResultData
     */
    @Log(title = "删除参数配置", businessType = BusinessType.DELETE)
    @RequestMapping(value = "/delete/{configid}", method = {RequestMethod.DELETE})
    public R<Boolean> delete(@PathVariable Integer configid) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = sysconfigService.delete(configid);
        return R.ok(flag);
    }

    /**
     * 根据参数键名获取参数配置
     *
     * @param configkey 参数键名
     * @return ResultData
     */
    @Log(title = "根据参数键名获取参数配置", businessType = BusinessType.SELECT)
    @RequestMapping(value = "/configKey/{configkey}", method = {RequestMethod.GET})
    public R<SysConfig> getByConfigKey(@PathVariable String configkey) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        SysConfig sysconfig = sysconfigService.getByConfigKey(configkey);
        return R.ok(sysconfig);
    }



}