package com.rufeng.system.business.controller;


import com.baomidou.mybatisplus.core.metadata.IPage;
import com.rufeng.common.core.db.Pager;
import com.rufeng.common.core.web.domain.R;
import com.rufeng.common.log.annotation.Log;
import com.rufeng.common.log.enums.BusinessType;
import com.rufeng.system.business.domain.po.SysDictType;
import com.rufeng.system.business.service.ISysDictTypeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;


/**
 * 字典类型控制器
 *
 * @version v1.0.0
 * @since jdk1.8+
 */
@RestController
@RequestMapping("dict/type")
public class SysDictTypeController {

    @Autowired
    private ISysDictTypeService sysdicttypeService;

    /**
     * 获取字典类型
     *
     * @param dictid 字典主键
     * @return ResultData
     */
    @Log(title = "获取字典类型", businessType = BusinessType.OTHER)
    @RequestMapping(value = "/get/{dictid}", method = {RequestMethod.GET})
    public R<SysDictType> get(@PathVariable Integer dictid) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        SysDictType dictType = sysdicttypeService.get(dictid);
        return R.ok(dictType);
    }

    /**
     * 查询字典类型
     *
     * @param sysdicttype 字典类型对象
     * @return ResultData
     */
    @RequestMapping(value = "/list", method = {RequestMethod.GET})
    public R<List<SysDictType>> list(SysDictType sysdicttype) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        List<SysDictType> list = sysdicttypeService.list(sysdicttype);
        return R.ok(list);
    }


    /**
     * 分页查询字典类型
     *
     * @param page        分页对象
     * @param sysdicttype 字典类型对象
     * @return ResultData
     */
    @RequestMapping(value = "/list-by-page", method = {RequestMethod.GET})
    public R<IPage<SysDictType>> listPager(SysDictType sysdicttype, Pager page) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        IPage<SysDictType> dictTypeIPage = sysdicttypeService.listPager(sysdicttype, page);
        return R.ok(dictTypeIPage);
    }

    /**
     * 添加字典类型
     *
     * @param sysdicttype 字典类型对象
     * @return ResultData
     */
    @Log(title = "添加字典类型", businessType = BusinessType.INSERT)
    @RequestMapping(value = "/add", method = {RequestMethod.POST})
    public R<Boolean> add(@RequestBody SysDictType sysdicttype) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = sysdicttypeService.add(sysdicttype);
        return R.ok(flag);
    }

    /**
     * 更新字典类型
     *
     * @param sysdicttype 字典类型对象
     * @return ResultData
     */
    @Log(title = "添加字典类型", businessType = BusinessType.UPDATE)
    @RequestMapping(value = "/update", method = {RequestMethod.PUT})
    public R<Boolean> update(@RequestBody SysDictType sysdicttype) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = sysdicttypeService.update(sysdicttype);
        return R.ok(flag);
    }

    /**
     * 删除字典类型
     *
     * @param dictid 字典主键
     * @return ResultData
     */
    @Log(title = "添加字典类型", businessType = BusinessType.DELETE)
    @RequestMapping(value = "/delete/{dictid}", method = {RequestMethod.DELETE})
    public R<Boolean> delete(@PathVariable Integer dictid) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = sysdicttypeService.delete(dictid);
        return R.ok(flag);
    }
}