package com.rufeng.system.business.controller;


import com.baomidou.mybatisplus.core.metadata.IPage;
import com.rufeng.common.core.db.Pager;
import com.rufeng.common.core.web.controller.BaseController;
import com.rufeng.common.core.web.domain.R;
import com.rufeng.common.log.annotation.Log;
import com.rufeng.common.log.enums.BusinessType;
import com.rufeng.system.business.domain.po.SysDictData;
import com.rufeng.system.business.service.ISysDictDataService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;


/**
 * 字典数据控制器
 *
 * @version v1.0.0
 * @since jdk1.8+
 */
@RestController
@RequestMapping("dict/data")
public class SysDictDataController extends BaseController {
    private Logger log = LoggerFactory.getLogger(SysDictDataController.class);

    @Autowired
    private ISysDictDataService sysdictdataService;

    /**
     * 获取字典数据
     *
     * @param dictcode 字典编码
     * @return ResultData
     */
    @Log(title = "添加字典数据", businessType = BusinessType.INSERT)
    @RequestMapping(value = "/get/{dictcode}", method = {RequestMethod.GET})
    public R<SysDictData> get(@PathVariable Integer dictcode) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        SysDictData dictData = sysdictdataService.get(dictcode);
        return R.ok(dictData);

    }

    /**
     * 查询字典数据
     *
     * @param sysdictdata 字典数据对象
     * @return ResultData
     */
    @RequestMapping(value = "/list", method = {RequestMethod.GET})
    public R<List<SysDictData>> list(SysDictData sysdictdata) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        List<SysDictData> list = sysdictdataService.list(sysdictdata);
        return R.ok(list);
    }


    /**
     * 分页查询字典数据
     *
     * @param page        分页对象
     * @param sysdictdata 字典数据对象
     * @return ResultData
     */
    @RequestMapping(value = "/list-by-page", method = {RequestMethod.GET})
    public R<IPage<SysDictData>> listPager(SysDictData sysdictdata, Pager page) throws Exception {
        IPage<SysDictData> dictDataIPage = sysdictdataService.listPager(sysdictdata, page);
        return R.ok(dictDataIPage);
    }

    /**
     * 添加字典数据
     *
     * @param sysdictdata 字典数据对象
     * @return ResultData
     */
    @Log(title = "添加字典数据", businessType = BusinessType.INSERT)
    @RequestMapping(value = "/add", method = {RequestMethod.POST})
    public R<Boolean> add(@RequestBody SysDictData sysdictdata) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = sysdictdataService.add(sysdictdata);
        return R.ok(flag);
    }

    /**
     * 更新字典数据
     *
     * @param sysdictdata 字典数据对象
     * @return ResultData
     */
    @Log(title = "更新字典数据", businessType = BusinessType.UPDATE)
    @RequestMapping(value = "/update", method = {RequestMethod.PUT})
    public R<Boolean> update(@RequestBody SysDictData sysdictdata) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = sysdictdataService.update(sysdictdata);
        return R.ok(flag);
    }

    /**
     * 删除字典数据
     *
     * @param dictcode 字典编码
     * @return ResultData
     */
    @Log(title = "删除字典数据", businessType = BusinessType.DELETE)
    @RequestMapping(value = "/delete/{dictcode}", method = {RequestMethod.DELETE})
    public R<Boolean> delete(@PathVariable Integer dictcode) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = sysdictdataService.delete(dictcode);
        return R.ok(flag);
    }

}