package com.rufeng.system.business.controller;

import com.baomidou.mybatisplus.core.metadata.IPage;
import com.rufeng.common.core.db.Pager;
import com.rufeng.common.core.web.controller.BaseController;
import com.rufeng.common.core.web.domain.R;
import com.rufeng.system.api.domain.SysRole;
import com.rufeng.system.business.domain.po.SysPost;
import com.rufeng.system.business.service.ISysPostService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * 岗位信息  控制器
 *
 * @auther chengen
 * @date 2020/12/18 18:38
 */
@RestController
@RequestMapping("post")
public class SysPostController extends BaseController {
    @Autowired
    private ISysPostService sysPostService;

    /**
     * 根据岗位id获取岗位信息
     *
     * @param postid 岗位ID
     * @return ResultData
     */
    @RequestMapping(value = "/get/{postid}", method = RequestMethod.GET)
    public R<SysPost> get(@PathVariable Integer postid) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        SysPost sysPost = sysPostService.get(postid);
        return R.ok(sysPost);
    }

    /**
     * 查询岗位信息
     *
     * @param sysPost 岗位信息对象
     * @return ResultData
     */
    @RequestMapping(value = "/list", method = {RequestMethod.GET})
    public R<List<SysPost>> list(SysPost sysPost) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        List<SysPost> list = sysPostService.list(sysPost);
        return R.ok(list);
    }

    /**
     * 分页查询岗位信息
     *
     * @param page    分页对象
     * @param sysPost 岗位信息对象
     * @return ResultData
     */
    @RequestMapping(value = "/list-by-page", method = {RequestMethod.GET})
    public R<IPage<SysPost>> listPager(SysPost sysPost, Pager page) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        IPage<SysPost> sysUserIPage = sysPostService.listPager(sysPost, page);
        return R.ok(sysUserIPage);
    }

    /**
     * 添加岗位信息
     */
    @RequestMapping(value = "/save", method = {RequestMethod.POST})
    public R<Boolean> saveSysUser(@RequestBody SysPost sysPost) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = sysPostService.saveSysPost(sysPost);
        return R.ok(flag);
    }


    /**
     * 修改岗位信息
     */
    @RequestMapping(value = "/update", method = {RequestMethod.PUT})
    public R<Boolean> updateSysUser(@RequestBody SysPost sysPost) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = sysPostService.updateSysPost(sysPost);
        return R.ok(flag);
    }

    /**
     * 删除岗位信息
     */
    @RequestMapping(value = "/delete/{postid}", method = {RequestMethod.DELETE})
    public R<Boolean> deleteSysUser(@PathVariable Integer postid) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = sysPostService.deleteSysPost(postid);
        return R.ok(flag);
    }
}
