package com.rufeng.system.service.impl;


import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.rufeng.common.core.domain.R;
import com.rufeng.common.core.web.domain.ResultData;
import com.rufeng.system.api.domain.SysUser;
import com.rufeng.system.api.model.LoginUser;
import com.rufeng.system.mapper.ISysUserDao;
import com.rufeng.system.service.ISysUserService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;


/**
 * 用户信息 服务接口实现
 *
 * @version v1.0.0
 * @since jdk1.8+
 */
@Service
public class SysUserServiceImpl  implements ISysUserService {
    private Logger log = LoggerFactory.getLogger(SysUserServiceImpl.class);

    @Autowired
    private ISysUserDao sysuserDao;


    @Override
    public R<LoginUser> get(String userid) throws Exception {
        log.debug("###[服务] 开始查询用户信息 userid=[{}]. ", userid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        SysUser sysuser = sysuserDao.selectById(userid);
        LoginUser sysUserVo = new LoginUser();
        sysUserVo.setUser(sysuser);
        log.info("###[服务] 完成查询用户信息 sysUserVo=[{}]", sysUserVo);
        return R.ok(sysUserVo);
    }


}
