package com.rufeng.system.controller;


import com.rufeng.common.core.domain.R;
import com.rufeng.common.core.web.domain.ResultData;
import com.rufeng.system.api.model.LoginUser;
import com.rufeng.system.service.ISysUserService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;


/**
 * 用户信息控制器
 *
 * @version v1.0.0
 * @since jdk1.8+
 */
@RestController
@RequestMapping("/system/sysuser")
public class SysUserController {
    private Logger log = LoggerFactory.getLogger(SysUserController.class);

    @Autowired
    private ISysUserService sysuserService;

    /**
     * 获取用户信息
     *
     * @param user_id 用户ID
     * @return ResultData
     */
    @RequestMapping(value = "/get/{id}", method = {RequestMethod.GET, RequestMethod.POST})
    public R<LoginUser> get(@PathVariable String id) throws Exception {
        log.debug("###开始查询用户信息， user_id=[{}].", id);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        return sysuserService.get(id);
    }
}