package com.rufeng.system.business.service.impl;


import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.rufeng.common.core.db.Pager;
import com.rufeng.system.business.domain.po.SysConfig;
import com.rufeng.system.business.mapper.ISysConfigDao;
import com.rufeng.system.business.service.ISysConfigService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;


/**
 * 参数配置 服务接口实现
 *
 * @version v1.0.0
 * @auther chengen
 * @date 2020/12/18 18:24
 */
@Service
public class SysConfigServiceImpl extends ServiceImpl<ISysConfigDao, SysConfig> implements ISysConfigService {
    private Logger log = LoggerFactory.getLogger(SysConfigServiceImpl.class);

    @Autowired
    private ISysConfigDao sysconfigDao;

    @Override
    public SysConfig get(String config_id) throws Exception {
        log.debug("###[服务] 开始查询参数配置 config_id=[{}]. ", config_id);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        SysConfig sysconfig = getById(config_id);
        log.info("###[服务] 完成查询参数配置 sysconfig=[{}]", sysconfig);
        return sysconfig;
    }

    @Override
    public List<SysConfig> list(SysConfig sysconfig) throws Exception {
        log.debug("###[服务] 开始根据条件{}查询参数配置", sysconfig);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        QueryWrapper<SysConfig> sysconfigWrapper = new QueryWrapper<>();
        sysconfigWrapper.setEntity(sysconfig);
        List<SysConfig> sysconfigs = list(sysconfigWrapper);
        log.info("###[服务] 完成查询参数配置 sysconfigs=[{}]", sysconfigs);
        return sysconfigs;
    }

    @Override
    public IPage<SysConfig> listPager(SysConfig sysconfig, Pager page) throws Exception {
        log.debug("###[服务] 开始根据条件{}分页查询参数配置", sysconfig);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        Page<SysConfig> pageParam = new Page<>(page.getCurrentPage(), page.getTotalSize()); // 当前页码，每页条数
        QueryWrapper<SysConfig> sysconfigWrapper = new QueryWrapper<>();
        sysconfigWrapper.setEntity(sysconfig);
        IPage<SysConfig> pu = page(pageParam, sysconfigWrapper);
        log.info("###[服务] 完成分页查询参数配置 pu=[{}]", pu);
        return pu;
    }

    @Override
    public boolean add(SysConfig sysconfig) throws Exception {
        log.debug("###[服务] 开始添加新参数配置, sysconfig=[{}]", sysconfig);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = save(sysconfig);
        log.info("###[服务] 完成添加新参数配置，flag=[{}]", flag);
        return flag;
    }

    @Override
    public boolean update(SysConfig sysconfig) throws Exception {
        log.debug("###[服务] 开始根据条件{}修改参数配置,sysconfig=[{}]", sysconfig);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = updateById(sysconfig);
        log.info("###[服务] 完成修改参数配置，flag=[{}]", flag);
        return flag;
    }

    @Override
    public boolean delete(Integer configid) throws Exception {
        log.debug("###[服务] 开始根据条件id{}删除参数配置,configid=[{}]", configid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = removeById(configid);
        log.info("###[服务] 完成删除参数配置，flag=[{}]", flag);
        return flag;
    }
}
