package com.rufeng.system.business.service.impl;


import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.rufeng.common.core.db.Pager;
import com.rufeng.system.api.domain.SysDept;
import com.rufeng.system.business.mapper.ISysDeptDao;
import com.rufeng.system.business.service.ISysDeptService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;


/**
 * 部门 服务接口实现
 *
 * @version v1.0.0
 * @auther chengen
 * @date 2020/12/18 18:24
 */
@Service
public class SysDeptServiceImpl extends ServiceImpl<ISysDeptDao, SysDept> implements ISysDeptService {
    private Logger log = LoggerFactory.getLogger(SysDeptServiceImpl.class);

    @Autowired
    private ISysDeptDao sysdeptDao;

    @Override
    public SysDept get(Integer deptid) throws Exception {
        log.debug("###[服务] 开始查询部门 deptid=[{}]. ", deptid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        SysDept sysdept = getById(deptid);
        log.info("###[服务] 完成查询部门 sysdept=[{}]", sysdept);
        return sysdept;
    }

    @Override
    public List<SysDept> list(SysDept sysdept) throws Exception {
        log.debug("###[服务] 开始根据条件{}查询部门,sysdept=[{}]", sysdept);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        QueryWrapper<SysDept> sysdeptWrapper = new QueryWrapper<>();
        sysdeptWrapper.setEntity(sysdept);
        List<SysDept> sysdepts = list(sysdeptWrapper);
        log.info("###[服务] 完成查询部门 sysdepts=[{}]", sysdepts);
        return sysdepts;
    }

    @Override
    public IPage<SysDept> listPager(SysDept sysdept, Pager page) throws Exception {
        log.debug("###[服务] 开始根据条件{}分页查询部门,sysdept=[{}]", sysdept);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        Page<SysDept> pageParam = new Page<>(page.getCurrentPage(), page.getTotalSize()); // 当前页码，每页条数
        QueryWrapper<SysDept> sysdeptWrapper = new QueryWrapper<>();
        sysdeptWrapper.setEntity(sysdept);
        IPage<SysDept> pu = page(pageParam, sysdeptWrapper);
        log.info("###[服务] 完成分页查询部门 pu=[{}]", pu);
        return pu;
    }

    @Override
    public boolean add(SysDept sysdept) throws Exception {
        log.debug("###[服务] 开始添加新部门,sysdept=[{}]", sysdept);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = save(sysdept);
        log.info("###[服务] 完成添加新部门，flag=[{}]", flag);
        return flag;
    }

    @Override
    public boolean update(SysDept sysdept) throws Exception {
        log.debug("###[服务] 开始根据条件{}修改部门,", sysdept);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = updateById(sysdept);
        log.info("###[服务] 完成修改部门，flag=[{}]", flag);
        return flag;
    }

    @Override
    public boolean delete(Integer deptid) throws Exception {
        log.debug("###[服务] 开始根据条件{}删除部门,deptid=[{}]", deptid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = removeById(deptid);
        log.info("###[服务] 完成删除部门，flag=[{}]", flag);
        return flag;
    }
}

