package com.rufeng.system.business.service.impl;


import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.rufeng.common.core.db.Pager;
import com.rufeng.system.business.domain.po.SysMenu;
import com.rufeng.system.business.mapper.ISysMenuDao;
import com.rufeng.system.business.service.ISysMenuService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;


/**
 * 菜单权限 服务接口实现
 *
 * @version v1.0.0
 * @auther chengen
 * @date 2020/12/18 18:24
 */
@Service
public class SysMenuServiceImpl extends ServiceImpl<ISysMenuDao, SysMenu> implements ISysMenuService {
    private Logger log = LoggerFactory.getLogger(SysMenuServiceImpl.class);

    @Autowired
    private ISysMenuDao sysmenuDao;

    @Override
    public SysMenu get(Integer menuid) throws Exception {
        log.debug("###[服务] 开始查询菜单权限 menuid=[{}]. ", menuid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        SysMenu menu = sysmenuDao.selectById(menuid);
        log.info("###[服务] 完成查询菜单权限 menu=[{}]", menu);
        return menu;
    }

    @Override
    public List<SysMenu> list(SysMenu sysmenu) throws Exception {
        log.debug("###[服务] 开始根据条件{}查询菜单权限,menu=[{}]", sysmenu);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        QueryWrapper<SysMenu> sysmenuWrapper = new QueryWrapper<>();
        sysmenuWrapper.setEntity(sysmenu);
        List<SysMenu> menus = sysmenuDao.selectList(sysmenuWrapper);
        log.info("###[服务] 完成查询菜单权限 menus=[{}]", menus);
        return menus;
    }

    @Override
    public IPage<SysMenu> listPager(SysMenu sysmenu, Pager page) throws Exception {
        log.debug("###[服务] 开始根据条件{}分页查询菜单权限,sysmenu=[{}],page=[{}]", sysmenu, page);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        Page<SysMenu> pageParam = new Page<>(page.getCurrentPage(), page.getTotalSize()); // 当前页码，每页条数
        QueryWrapper<SysMenu> sysmenuWrapper = new QueryWrapper<>();
        sysmenuWrapper.setEntity(sysmenu);
        IPage<SysMenu> pu = page(pageParam, sysmenuWrapper);
        log.info("###[服务] 完成分页查询菜单权限 pu=[{}]", pu);
        return pu;
    }

    @Override
    public boolean add(SysMenu menu) throws Exception {
        log.debug("###[服务] 开始添加新菜单权限, menu=[{}]", menu);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = save(menu);
        log.info("###[服务] 完成添加新菜单权限，flag=[{}]", flag);
        return flag;
    }

    @Override
    public boolean update(SysMenu menu) throws Exception {
        log.debug("###[服务] 开始根据条件{}修改菜单权限,menu=[{}]", menu);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = updateById(menu);
        log.info("###[服务] 完成修改菜单权限，flag=[{}]", flag);
        return flag;
    }

    @Override
    public boolean delete(Integer menuid) throws Exception {
        log.debug("###[服务] 开始根据条件{}删除菜单权限,menuid=[{}]", menuid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = removeById(menuid);
        log.info("###[服务] 完成删除菜单权限，flag=[{}]", flag);
        return flag;
    }
}
