package com.rufeng.system.business.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.rufeng.common.core.db.Pager;
import com.rufeng.system.api.domain.SysRole;
import com.rufeng.system.business.mapper.ISysRoleDao;
import com.rufeng.system.business.service.ISysRoleService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * 角色信息 服务接口实现
 *
 * @version v1.0.0
 * @auther chengen
 * @date 2020/12/18 18:24
 */
@Service
public class SysRoleServiceImpl extends ServiceImpl<ISysRoleDao, SysRole> implements ISysRoleService {
    private Logger log = LoggerFactory.getLogger(SysRoleServiceImpl.class);
    @Autowired
    private ISysRoleDao sysRoleDao;

    @Override
    public SysRole get(Integer roleid) throws Exception {
        log.debug("###[服务] 开始查询角色信息 roleid=[{}]. ", roleid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        SysRole sysRole = getById(roleid);
        log.info("###[服务] 完成查询角色信息 sysRole=[{}]", sysRole);
        return sysRole;
    }

    @Override
    public List<SysRole> list(SysRole sysRole) {
        log.debug("###[服务] 开始根据条件{}查询角色信息,sysRole=[{}]", sysRole);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        QueryWrapper<SysRole> queryWrapper = new QueryWrapper<>();
        List<SysRole> list = list(queryWrapper);
        log.info("###[服务] 完成分页查询角色信息 list=[{}]", list);
        return list;
    }

    @Override
    public IPage<SysRole> listPager(SysRole sysRole, Pager page) throws Exception {
        log.debug("###[服务] 开始根据条件分页查询角色信息,sysRole=[{}],page=[{}]", sysRole, page);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        Page<SysRole> pageParam = new Page<>(page.getCurrentPage(), page.getTotalSize()); // 当前页码，每页条数
        QueryWrapper<SysRole> userQueryWrapper = new QueryWrapper<>();
        userQueryWrapper.setEntity(sysRole);
        IPage<SysRole> pu = page(pageParam, userQueryWrapper);
        log.info("###[服务] 完成分页查询角色信息 pu=[{}]", pu);
        return pu;
    }

    @Override
    public boolean saveSysRole(SysRole sysRole) throws Exception {
        log.debug("###[服务] 开始根据角色id删除角色信息 sysRole=[{}]", sysRole);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = save(sysRole);
        log.info("###[服务] 完成根据角色id删除角色信息 flag=[{}]", flag);
        return flag;
    }

    @Override
    public boolean updateSysRole(SysRole sysRole) throws Exception {
        log.debug("###[服务] 开始根据角色id{}更新角色信息 sysRole=[{}]", sysRole.getRoleid(), sysRole);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = updateById(sysRole);
        log.info("###[服务] 完成根据角色id更新角色信息 flag=[{}]", flag);
        return flag;
    }

    @Override
    public boolean deleteSysRole(Integer roleid) throws Exception {
        log.debug("###[服务] 开始根据角色id删除角色信息 roleid=[{}]", roleid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = removeById(roleid);
        log.info("###[服务] 完成根据角色id删除角色信息 flag=[{}]", flag);
        return flag;
    }
}
