package com.rufeng.system.business.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.rufeng.common.core.db.Pager;
import com.rufeng.common.core.utils.StringUtils;
import com.rufeng.system.api.domain.SysRole;
import com.rufeng.system.business.domain.po.SysRoleMenu;
import com.rufeng.system.business.mapper.ISysMenuDao;
import com.rufeng.system.business.mapper.ISysRoleDao;
import com.rufeng.system.business.service.ISysMenuService;
import com.rufeng.system.business.service.ISysRoleMenuService;
import com.rufeng.system.business.service.ISysRoleService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.jsf.FacesContextUtils;

import java.awt.geom.FlatteningPathIterator;
import java.util.*;

/**
 * 角色信息 服务接口实现
 *
 * @version v1.0.0
 * @auther chengen
 * @date 2020/12/18 18:24
 */
@Service
public class SysRoleServiceImpl extends ServiceImpl<ISysRoleDao, SysRole> implements ISysRoleService {
    private Logger log = LoggerFactory.getLogger(SysRoleServiceImpl.class);
    @Autowired
    private ISysRoleDao sysRoleDao;
    @Autowired
    private ISysRoleMenuService sysRoleMenuService;

    @Override
    public SysRole get(Integer roleid) throws Exception {
        log.debug("###[服务] 开始查询角色信息 roleid=[{}]. ", roleid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        SysRole sysRole = sysRoleDao.selectRoleById(roleid);
        log.info("###[服务] 完成查询角色信息 sysRole=[{}]", sysRole);
        return sysRole;
    }

    @Override
    public List<SysRole> list(SysRole sysRole) {
        log.debug("###[服务] 开始根据条件{}查询角色信息,sysRole=[{}]", sysRole);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        QueryWrapper<SysRole> queryWrapper = new QueryWrapper<>();
        List<SysRole> list = list(queryWrapper);
        log.info("###[服务] 完成查询角色信息 list=[{}]", list);
        return list;
    }

    @Override
    public IPage<SysRole> listPager(SysRole sysRole, Pager page) throws Exception {
        log.debug("###[服务] 开始根据条件分页查询角色信息,sysRole=[{}],page=[{}]", sysRole, page);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        Page<SysRole> pageParam = new Page<>(page.getCurrentPage(), page.getTotalSize()); // 当前页码，每页条数
        QueryWrapper<SysRole> userQueryWrapper = new QueryWrapper<>();
        userQueryWrapper.setEntity(sysRole);
        IPage<SysRole> pu = page(pageParam, userQueryWrapper);
        log.info("###[服务] 完成分页查询角色信息 pu=[{}]", pu);
        return pu;
    }

    @Override
    public boolean saveSysRole(SysRole sysRole) throws Exception {
        log.debug("###[服务] 开始根据角色id添加角色信息 sysRole=[{}]", sysRole);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = save(sysRole);
        flag = insertRoleMenu(sysRole);
        log.info("###[服务] 完成根据角色id添加角色信息 flag=[{}]", flag);
        return flag;
    }

    @Override
    public boolean updateSysRole(SysRole sysRole) throws Exception {
        log.debug("###[服务] 开始根据角色id{}更新角色信息 sysRole=[{}]", sysRole.getRoleid(), sysRole);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = updateById(sysRole);
        sysRoleMenuService.deleteSysRole(sysRole.getRoleid());
        flag = insertRoleMenu(sysRole);
        log.info("###[服务] 完成根据角色id更新角色信息 flag=[{}]", flag);
        return flag;
    }

    @Override
    public boolean deleteSysRole(Integer roleid) throws Exception {
        log.debug("###[服务] 开始根据角色id删除角色信息 roleid=[{}]", roleid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = removeById(roleid);
        flag = sysRoleMenuService.deleteSysRole(roleid);
        log.info("###[服务] 完成根据角色id删除角色信息 flag=[{}]", flag);
        return flag;
    }

    @Override
    public Set<String> selecteRolePermissionByUserId(Integer userId) {
        log.debug("###[服务] 开始根据用户id查询角色信息 userId=[{}]", userId);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        Set<String> permsSet = new HashSet<>();
        List<SysRole> perms = sysRoleDao.selectPermissionByUserId(userId);
        for (SysRole perm : perms) {
            permsSet.addAll(Arrays.asList(perm.getRolekey().trim().split(",")));
        }
        log.info("###[服务] 完成根据用户id查询角色信息 permsSet=[{}]", permsSet);
        return null;
    }


    /**
     * 新增角色菜单信息
     *
     * @param role 角色对象
     */
    public boolean insertRoleMenu(SysRole role) {
        log.debug("###[服务] 开始根据角色与菜单关系信息 role=[{}]", role);
        boolean flag = false;
        // 新增用户与角色管理
        List<SysRoleMenu> list = new ArrayList<>();
        for (Integer menuid : role.getMenuIds()) {
            SysRoleMenu rm = new SysRoleMenu();
            rm.setRoleid(role.getRoleid());
            rm.setMenuid(menuid);
            list.add(rm);
        }
        if (list.size() > 0) {
            flag = sysRoleMenuService.saveBatch(list);
        }
        return flag;
    }

}
