package com.rufeng.system.business.service.impl;


import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.rufeng.common.core.db.Pager;
import com.rufeng.common.core.web.domain.R;
import com.rufeng.common.core.web.domain.ResultData;
import com.rufeng.system.api.domain.SysUser;
import com.rufeng.system.api.model.LoginUser;
import com.rufeng.system.business.mapper.ISysUserDao;
import com.rufeng.system.business.service.ISysUserService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;


/**
 * 用户信息 服务接口实现
 *
 * @version v1.0.0
 * @since jdk1.8+
 */
@Service
public class SysUserServiceImpl extends ServiceImpl<ISysUserDao, SysUser> implements ISysUserService {
    private Logger log = LoggerFactory.getLogger(SysUserServiceImpl.class);

    @Autowired
    private ISysUserDao sysuserDao;


    @Override
    public R<LoginUser> get(String userid) throws Exception {
        log.debug("###[服务] 开始查询用户信息 userid=[{}]. ", userid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        SysUser sysuser = sysuserDao.selectById(userid);
        LoginUser sysUserVo = new LoginUser();
        sysUserVo.setUser(sysuser);
        log.info("###[服务] 完成查询用户信息 sysUserVo=[{}]", sysUserVo);
        return R.ok(sysUserVo);
    }

    @Override
    public ResultData listPager(SysUser sysuser, Pager page) throws Exception {
        log.debug("###[服务] 开始根据条件{}分页查询用户信息", sysuser);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();

        Page<SysUser> pageParam = new Page<>(page.getCurrentPage(), page.getTotalSize()); // 当前页码，每页条数
        QueryWrapper<SysUser> userQueryWrapper = new QueryWrapper<>();
        userQueryWrapper.setEntity(sysuser);
        IPage<SysUser> pu = sysuserDao.selectPage(pageParam, userQueryWrapper);
        resData.setData(pu);
        log.info("###[服务] 完成分页查询用户信息 resData=[{}]", resData);
        return resData;
    }

}
