package com.rufeng.system.business.controller;


import com.baomidou.mybatisplus.core.metadata.IPage;
import com.rufeng.common.core.db.Pager;
import com.rufeng.common.core.web.controller.BaseController;
import com.rufeng.common.core.web.domain.R;
import com.rufeng.system.api.domain.SysOperLog;
import com.rufeng.system.business.service.ISysOperLogService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;


/**
 * 操作日志记录控制器
 *
 * @version v1.0.0
 * @since jdk1.8+
 */
@RestController
@RequestMapping("operlog")
public class SysOperLogController extends BaseController {

    @Autowired
    private ISysOperLogService sysoperlogService;

    /**
     * 获取操作日志记录
     *
     * @param operid 日志主键
     * @return ResultData
     */
    @RequestMapping(value = "/get/{operid}", method = {RequestMethod.GET})
    public R<SysOperLog> get(@PathVariable Integer operid) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        SysOperLog operLog = sysoperlogService.get(operid);
        return R.ok(operLog);
    }

    /**
     * 查询操作日志记录
     *
     * @param operLog 操作日志记录对象
     * @return ResultData
     */
    @RequestMapping(value = "/list", method = {RequestMethod.GET})
    public R<List<SysOperLog>> list(SysOperLog operLog) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        List<SysOperLog> list = sysoperlogService.list(operLog);
        return R.ok(list);
    }


    /**
     * 分页查询操作日志记录
     *
     * @param page    分页对象
     * @param operLog 操作日志记录对象
     * @return ResultData
     */
    @RequestMapping(value = "/list-by-page", method = {RequestMethod.GET})
    public R<IPage<SysOperLog>> listPager(SysOperLog operLog, Pager page) throws Exception {
        IPage<SysOperLog> operLogIPage = sysoperlogService.listPager(operLog, page);
        return R.ok(operLogIPage);
    }

    /**
     * 添加操作日志记录
     *
     * @param operLog 操作日志记录对象
     * @return ResultData
     */
    @RequestMapping(value = "/add", method = {RequestMethod.POST})
    public R<Boolean> add(@RequestBody SysOperLog operLog) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = sysoperlogService.add(operLog);
        return R.ok(flag);
    }

    /**
     * 更新操作日志记录
     *
     * @param operLog 操作日志记录对象
     * @return ResultData
     */
    @RequestMapping(value = "/update", method = {RequestMethod.PUT})
    public R<Boolean> update(@RequestBody SysOperLog operLog) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = sysoperlogService.update(operLog);
        return R.ok(flag);
    }

    /**
     * 删除操作日志记录
     *
     * @param operid 日志主键
     * @return ResultData
     */
    @RequestMapping(value = "/delete/{operid}", method = {RequestMethod.DELETE})
    public R<Boolean> delete(@PathVariable Integer operid) throws Exception {
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        boolean flag = sysoperlogService.delete(operid);
        return R.ok(flag);
    }
}